old=open('before230.html','r',encoding='utf-8-sig').read()
new=open('map.html','r',encoding='utf-8').read()
print('=== BEFORE: #app 주변 HTML ===')
i=old.find('id="app"')
if i>0: print(old[i:i+400])
print()
print('=== NOW: #app 주변 HTML ===')
i=new.find('id="app"')
if i>0: print(new[i:i+600])
